routeEnhancers:
  SimpleConsent:
    type: Extbase
    namespace: 'tx_simpleconsent_consent'
    routes:
      - routePath: '/consent/show/{hash}'
        _controller: 'Consent::show'
      - routePath: '/consent/confirm/{address}'
        _controller: 'Consent::confirm'
      - routePath: '/consent/delete/{address}'
        _controller: 'Consent::delete'
    defaultController: 'Consent::show'
    requirements:
      hash: '[a-zA-Z0-9]{30}'
      address: '[0-9]{0,}'
